### ISSUE TITLE
Norton Removed "Generate.exe"

### ISSUE THREAD

**Issue by MasterGuns7489** [PhytoEpidemic/stable-diffusion-webui-installation-manager#2]

**Comment by MasterGuns7489** [comment]
I went to the Microsoft Store, purchased "Stable Diffusion AI Image Generator (Automatic1111)" and ran the installer.  It installed fine but then Norton identified a major "Threat" and quickly removed "Generate.Exe".  Obviously this completely crippled the software I just paid for.  What is the solution to this major problem?

**Comment by PhytoEpidemic** [comment]
My apologies for such a late follow-up. Unfortunately most antivirus software will flag this program due to it's use of powershell and other lol (living off the land) techniques. I'm not sure where Generate.exe was coming from as I cannot find it in my installation. It could be a temporary file used by the webui. 

My recommendation to remedy this would be assign an exclusion in Norton to ignore the folder that it is installed to and then check the "Clean Install" checkbox before starting the server.
